---
- name: Use range
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5

  rules:
    - name: Just send it
      condition: event.i == 1
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: "Default"
